dist: trusty
language: cpp

addons:
  apt:
    packages:
      - libcppunit-dev
      - libboost-dev

os:
  - linux

env:
  global:
    - MAKEFLAGS="-j2"

before_install:
  # C++14
  - test "$TRAVIS_OS_NAME" != "linux" || sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - test "$TRAVIS_OS_NAME" != "linux" || sudo apt-get update -qq

install:
  # C++14
  - test "$TRAVIS_OS_NAME" != "linux" || sudo apt-get install -qq g++-5

script:
  - OPTIONS="--enable-test"
  - test "$TRAVIS_OS_NAME" != "linux" || export CC=gcc-5 CXX=g++-5
  - ./autogen.sh
  - ./configure --disable-silent-rules --disable-dependency-tracking $OPTIONS
  - make
  - make check
