dist: trusty
language: cpp

addons:
  apt:
    packages:
      - libcppunit-dev
      - libboost-dev

os:
  - linux

env:
  global:
    - MAKEFLAGS="-j2"

compiler:
  - gcc

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++14
  - sudo apt-get install -qq g++-5

script:
  - export CC=gcc-5 CXX=g++-5
  - ./autogen.sh
  - ./configure --enable-test
  - make
  - make check
